# Generated by Django 6.0 on 2026-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_alter_customer_id_alter_feedback_id_alter_orders_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.AddField(
            model_name='vendor',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/aadhar/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='aadhar_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_line',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/pan/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(default='ABCDE1234F', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
