# Generated by Django 6.0.2 on 2026-05-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='lon',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
